# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{class_factory}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pat Shaughnessy"]
  s.date = %q{2010-03-12}
  s.description = %q{Use syntax similar to factory_girl to create new ActiveRecord or other test classes (vs. instances of an existing model).}
  s.email = %q{pat@patshaughnessy.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "class_factory.gemspec",
     "lib/class_factory.rb",
     "lib/class_factory/class_factory.rb",
     "test/helper.rb",
     "test/test_active_records.rb",
     "test/test_plain_objects.rb"
  ]
  s.homepage = %q{http://patshaughnessy.net/class_factory}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Class Factory: Factory_girl-like syntax for dynamically creating Ruby classes}
  s.test_files = [
    "test/helper.rb",
     "test/test_active_records.rb",
     "test/test_plain_objects.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

